hostelapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.loginpage),
    path('login_details/', views.login_details),
    path('hostel_register/', views.hostel_register),
    path('hostel_admin/', views.hostel_admin),
    path('hostler/', views.hostler),
    path('hostel_admin/hostel_details/', views.hostel_details),
    path('hosteler/hosteler_details/', views.hosteler_details),
    path('emailGeneration/', views.emailGeneration),
    path('emailValidation/', views.emailValidation),
    path('hostel_admin/verify_hostlers_page/', views.verify_hostlers_page),
    path('hostel_admin/verify_hostler/<str:id>', views.verify_hostler),
    path('hostel_admin/delete_verify_hostler/<str:id>', views.delete_verify_hostler),
    path('hostel_admin/add_hostler/', views.add_hostler),
    path('hostel_admin/payment/', views.hostel_admin_payment),
    path('hostel_admin/payment_list/',views.hostel_admin_payment_list),
    path('hostler/complain/', views.hostler_complain),
    path('hostel_admin/all_hostler/', views.all_hostler),
    path('hostler/complain_status/', views.hostler_complain_status),
    path('hostel_admin/complain/', views.hostel_admin_complains),
    path('change_complain_status/<str:id>', views.change_complain_status),
    path('change_password/', views.change_password),
    path('hostler/receipt/', views.payment_receipt),
    path('forgot_password/', views.forgot_password),
    path('logout/', views.logout_user),
    # ajax
    path('check_hostler_email/', views.check_hostler_email),
    path('hostelNameChecker/', views.hostelNameChecker),
]

hostelproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hostelapp.urls')),
]

hostelapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class User(AbstractUser):
    is_warden_owner = models.BooleanField(default=False)
    is_hostler = models.BooleanField(default=False)
    username = models.EmailField(unique=True)
    mobile_no = models.IntegerField(null=True, blank=True)
    hostel_name = models.CharField(max_length=50, null=True, blank=True)
    details_status = models.BooleanField(default=False)
    addhar_no = models.CharField(max_length=12,null=True, blank=True)


class Hostel(models.Model):
    hostel_name_user = models.ForeignKey(User, on_delete=models.CASCADE)
    hostel_name = models.CharField(max_length=50, unique=True)
    address = models.CharField(max_length=100)
    no_of_rooms = models.IntegerField()

    def __str__(self):
        return self.hostel_name


class Hostel_verification(models.Model):
    hostel_name = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    name = models.CharField(max_length=25)
    email = models.EmailField()
    code = models.CharField(max_length=6)


class Complain(models.Model):
    STATUS = [
        ('solved', 'Solved'),
        ('pending', 'Pending'),
        ('returned', 'Returned'),
    ]
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    hostel_name = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    message = models.CharField(max_length=1000)
    complain_status = models.CharField(choices=STATUS, default="pending", max_length=8)
    date = models.DateField(default=timezone.now)


class Payment(models.Model):
    hostel_name = models.ForeignKey(Hostel, on_delete=models.CASCADE)
    slip_no = models.BigIntegerField()
    date = models.DateField(default=timezone.now)
    name = models.CharField(max_length=100)
    month_year = models.CharField(max_length=20)
    amount = models.IntegerField()
    remark = models.CharField(max_length=256,null=True,blank=True)

hostelapp/forms.py
from django import forms
from django.contrib.auth import authenticate
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password


class loginForm(forms.Form):
    username = forms.CharField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)


class user_creationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'first_name', 'last_name', 'mobile_no', 'is_warden_owner', 'hostel_name']
        widget = {
            'username': forms.EmailInput,
            'mobile_no': forms.NumberInput,
            'password': forms.PasswordInput,
            'is_warden_owner': forms.CheckboxInput,
        }

    def save(self, commit=True):
        user = super(user_creationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


hostelapp/views.py
from django.contrib.auth.hashers import check_password
from django.contrib.messages import error
from django.core.mail import send_mail
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect, HttpResponse
from django.template import loader
from hostelproject import settings
from .forms import *
from .models import *
import random
from email_validator import validate_email


def check_mailid(email):
    if validate_email(email, check_deliverability=False):
        return True
    else:
        return False


def password_generator():
    s = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    password = "".join(random.sample(s, 6))
    return password


def loginpage(request):
    form = loginForm()
    return render(request, 'loginpage.html', {'form': form})


def login_details(request):
    if request.session.has_key('logged_in_as_hostler'):
        return render(request, 'hostler.html')
    elif request.session.has_key('logged_in_as_admin'):
        return render(request, 'hostel_admin.html')
    elif request.method == 'POST':
        form = loginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if user.is_warden_owner:
                    login(request, user)
                    if user.details_status:
                        request.session['logged_in_as_admin'] = True
                        return render(request, 'hostel_admin.html')
                    else:
                        return redirect('/hostel_admin/hostel_details/')
                elif user.is_hostler:
                    login(request, user)
                    if user.details_status:
                        request.session['logged_in_as_hostler'] = True
                        return render(request, 'hostler.html')
                    else:
                        return redirect('/hosteler/hosteler_details/')
            else:
                error(request, 'Invalid username or password')
                return redirect(loginpage)
        else:
            error(request, 'Please enter the valid details')
            return redirect(loginpage)
    else:
        return redirect(loginpage)


def hostel_register(request):
    if request.method == 'POST':
        userform = user_creationForm(request.POST)
        if userform.is_valid:
            userform.save()
            return redirect(loginpage)
    userform = user_creationForm()
    return render(request, 'hostel_register.html', {'userform': userform})


def hostel_admin(request):
    return render(request, 'hostel_admin.html')


def hostel_details(request):
    if request.method == "POST":
        address = request.POST.get('hostel_address')
        no_of_rooms = request.POST.get('no_of_rooms')
        hostel_name = request.user
        Hostel(address=address, no_of_rooms=no_of_rooms, hostel_name_user=hostel_name,
               hostel_name=hostel_name.hostel_name).save()
        status = request.user
        status.details_status = True
        status.save()
        return render(request, 'hostel_admin.html')
    hostel_name = request.user.hostel_name
    return render(request, 'first/hostel_admin_first.html', {'hostel_name': hostel_name})


def hosteler_details(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        mobile_no = request.POST.get('mobile_no')
        addhar_no = request.POST.get('addhar_no')
        current_user = request.user
        current_user.first_name = first_name
        current_user.last_name = last_name
        current_user.mobile_no = mobile_no
        current_user.addhar_no = addhar_no
        current_user.details_status = True
        current_user.save()
        return render(request, 'hostler.html')
    else:
        hostel_name = request.user.hostel_name
        return render(request, 'first/hosteler_first.html', {'hostel_name': hostel_name})


def emailValidation(request):
    otp = request.POST.get('otp')
    if request.session['otp'] == otp:
        return HttpResponse('valid')
    else:
        return HttpResponse('not valid')


def add_hostler(request):
    entered_email = request.POST.get('hostler_email')
    code = password_generator()
    name = request.POST.get('name')
    request.session['otp'] = code
    html_message = loader.render_to_string('emails/add_hostler_email.html', {'otp': code})
    mail = send_mail('Email Verification', '', settings.EMAIL_HOST_USER, [entered_email],
                     html_message=html_message,
                     fail_silently=False)
    if mail:
        hostel = Hostel.objects.get(hostel_name=request.user.hostel_name)
        Hostel_verification(email=entered_email, code=code, name=name, hostel_name=hostel).save()
        return redirect('/hostel_admin/verify_hostlers_page/')
    else:
        error(request, 'enter the correct Email id')
        return redirect('/hostel_admin/verify_hostler/')


def verify_hostlers_page(request):
    Hostel_id = Hostel.objects.get(hostel_name=request.user.hostel_name)
    details = Hostel_verification.objects.filter(hostel_name=Hostel_id.id)
    return render(request, 'verify_hostler.html', {'details': details})


def verify_hostler(request, id):
    code = request.POST.get('code')
    hostler_code = Hostel_verification.objects.get(id=id)
    if hostler_code.code == code:
        generated_password = password_generator()
        html_message = loader.render_to_string('emails/hostler_credential.html', {'otp': generated_password})
        mail = send_mail('Email Verification', '', settings.EMAIL_HOST_USER, [hostler_code.email],
                         html_message=html_message,
                         fail_silently=True)
        if mail:
            password = make_password(generated_password)
            User(username=hostler_code.email, password=password, is_hostler=True,
                 hostel_name=request.user.hostel_name).save()
            hostler_code.delete()
            return redirect(login_details)
        else:
            # error(request, 'enter the correct Email id')
            return redirect(verify_hostlers_page)
    else:
        return redirect(verify_hostlers_page)


def delete_verify_hostler(request, id):
    hostler_details = Hostel_verification.objects.get(id=id)
    hostler_details.delete()
    return redirect(verify_hostlers_page)


def hostler(request):
    return render(request, 'hostler.html')


def hostler_complain(request):
    if request.method == "POST":
        name = request.user
        hostel_name = Hostel.objects.get(hostel_name=request.user.hostel_name)
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        Complain(name=name, hostel_name=hostel_name, subject=subject, message=message).save()
        return redirect('/hostler/complain_status/')
    else:
        return render(request, 'hostler_complain.html')


def hostler_complain_status(request):
    id = request.user.id
    data = Complain.objects.filter(name=id)
    return render(request, 'hostler_complain_status.html', {'data': data})


def hostel_admin_complains(request):
    Hostel_id = Hostel.objects.get(hostel_name=request.user.hostel_name)
    data = Complain.objects.filter(hostel_name=Hostel_id.id)
    return render(request, 'hostel_admin_complain_status.html', {'data': data})


def hostel_admin_payment(request):
    if request.method == "POST":
        hostel_id = Hostel.objects.get(hostel_name=request.user.hostel_name)
        hostel_name = Hostel.objects.get(hostel_name=hostel_id)
        slip_no = request.POST.get('slip_no')
        date = request.POST.get('date')
        name = request.POST.get('name')
        month_year = request.POST.get('month_year')
        amount = request.POST.get('amount')
        remark = request.POST.get('remark')
        Payment(hostel_name=hostel_name, slip_no=slip_no, date=date, name=name, month_year=month_year, amount=amount,
                remark=remark).save()
        return redirect('/hostel_admin/payment_list/')
    names = User.objects.filter(hostel_name=request.user.hostel_name).values_list('first_name', flat=True)
    hostel_id = Hostel.objects.get(hostel_name=request.user.hostel_name)
    slip_numbers = Payment.objects.filter(hostel_name=hostel_id).order_by('slip_no').values_list('slip_no', flat=True)
    try:
        slip_number = slip_numbers.last() + 1
    except:
        slip_number = 1
    return render(request, 'payment.html', {'names': names, 'slip_number': slip_number})


def hostel_admin_payment_list(request):
    hostel_id = Hostel.objects.get(hostel_name=request.user.hostel_name)
    data = Payment.objects.filter(hostel_name=hostel_id)
    return render(request, 'hostel_admin_payment_list.html', {'data': data})


def change_password(request):
    old_password = request.POST.get('old_password')
    new_password = request.POST.get('new_password')
    if check_password(old_password, request.user.password):
        request.user.password = make_password(new_password)
        request.user.save()
        username = request.user.username
        password = new_password
        user = authenticate(request, username=username, password=password)
        login(request, user)
        if user.is_warden_owner:
            request.session['logged_in_as_admin'] = True
            return render(request, 'hostel_admin.html')
        elif user.is_hostler:
            return render(request, 'hostler.html')
        return redirect('/login_details/')


def all_hostler(request):

hostelapp/templates/all_hostler.html
{% extends 'extends/hostel_admin_extends.html' %}
{% block content %}

<div class="container mt-5">
    <div class="mt-5" align="center"><h2>ALL HOSTLERS</h2></div>
    <table border="1" class="mt-2 w-100">
        <tr>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Email</td>
            <td>Mobile Number</td>
        </tr>
        {% for i in data %}
        <tr>
            <td>{{i.first_name|title}}</td>
            <td>{{i.last_name|title}}</td>
            <td>{{i.username}}</td>
            <td>{{i.mobile_no}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

hostelapp/templates/hostel_admin.html
{% extends 'extends/hostel_admin_extends.html' %}
{% block content %}
<div class="container mt-5 w-100" align="center">
    <div class="row">
        <div class="col-md-5 mt-5 offset-1 z-depth-3" style="background:#5CF7E7;">
            <div class="my-5">
                <a href="/hostel_admin/complain/">COMPLAINS</a>
            </div>
        </div>
        <div class="col-md-5 mt-5 offset-1 z-depth-3"" style="background:#5CF7E7;">
            <div class="my-5">
                HOSTLER
                <ul>
                    <li>
                        <a href="" data-toggle="modal"
                           data-target="#add_hostler">Add&nbsp;Hostler</a>
                    </li>
                    <li>
                        <a href="/hostel_admin/verify_hostlers_page/">Verify&nbsp;Hostler</a>
                    </li>
                    <li>
                        <a href="/hostel_admin/all_hostler/">All&nbsp;Hostler</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-5 mt-5 offset-1 z-depth-3" style="background:#5CF7E7;">
            <div class="my-5">
                <a class="nav-link" href="/hostel_admin/payment/">PAYMENTS</a>
                <a href="/hostel_admin/payment_list/">All PAYMENTS</a>
            </div>
        </div>
        <div class="col-md-5 mt-5 offset-1 z-depth-3" style="background:#5CF7E7;">
            <div class="my-5">
                <a class="nav-link" href="/hostel_admin/remove_hostler/">REMOVE&nbsp;HOSTLER</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

hostelapp/templates/hostel_admin_complain_status.html
{% extends 'extends/hostel_admin_extends.html' %}
{% block content %}
<div class="container mt-5 w-100" align="center">
    <div class="mt-5" align="center"><h2>Complains</h2></div>
    <table class="w-75" border="1">
        <tr>
            <td>Date</td>
            <td>Name</td>
            <td>Subject</td>
            <td>Message</td>
            <td></td>
        </tr>
        {% for i in data %}
        {{i.complain_status}}
        {% if i.complain_status == "pending" %}
        <tr>
            <td>{{i.date}}</td>
            <td>{{i.name.first_name}} {{i.name.last_name}}</td>
            <td>{{i.subject}}</td>
            <td>{{i.message}}</td>
            <td>
                <form method="post" action="/change_complain_status/{{i.id}}">{% csrf_token %}
                    <select name="status">Status
                        <option value="pending">Pending</option>
                        <option value="solved">Completed</option>
                        <option value="returned">Returned</option>
                    </select>
                    <button>Save</button>
                </form>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </table>
</div>
{% endblock %}

hostelapp/templates/hostel_admin_payment_list.html
{% extends 'extends/hostel_admin_extends.html' %}
{% block content %}
<div class="mt-5 container w-75" align="center">
    <div class="mt-3"><h2>All Payments</h2></div>
    <table class="mt-3 w-75">
        <tr>
            <td>Receipt Number</td>
            <td>Name</td>
            <td>Date</td>
            <td>year - month</td>
            <td>Amount</td>
        </tr>
        {% for i in data %}
        <tr>
            <td>{{i.slip_no}}</td>
            <td>{{i.name}}</td>
            <td>{{i.date}}</td>
            <td>{{i.month_year}}</td>
            <td>{{i.amount}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

hostelapp/templates/hostel_register.html
{% extends 'extends/basic.html' %}
{% block body%}
{% load widget_tweaks %}
{% load static %}
<script src="{% static 'js/hostel_creatation.js' %}"></script>
<style>
.vertical-center {
  margin: 0;
  position: absolute;
  top: 50%;
  -ms-transform: translateY(-50%);
  transform: translateY(-50%);
}
#id_address{
height:100px;
width:80%;
}

</style>
<div class="vertical-center text-center w-100">
    <div class="container w-50" style="background-color:rgba(0,0,0,.2)">
        <form action="/hostel_register/" id="hostelCreation" method="post" autocomplete="off">{% csrf_token %}
            <h1 class="text-center">
                Hostel Registration
            </h1>
            <div id="page1">
                <table class="table">
                    <tr>
                        <td>First Name</td>
                        <td>{{ userform.first_name}}</td>
                    <tr>
                        <td>Last Name</td>
                        <td>{{ userform.last_name }}<br></td>
                    </tr>
                    <tr>
                        <td>Mobile Number<br>
                            <span id="mobile_text"></span></td>
                        <td>{{ userform.mobile_no|attr:"oninput=mobileNumber()"}}</td>
                    </tr>
                    <tr>
                        <td>Hostel Name<br>
                            <span id="hostelName-text"></span></td>
                        <td>
                            {{userform.hostel_name|attr:"oninput=hostelNameChecker(this.value)"|attr:"onkeyup=this.value=this.value.toUpperCase()"}}
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>
                            <a class="material-tooltip-main" data-toggle="tooltip"
                               title="Next" onclick="nextPage()">
                                <font size="12">&#9654;</font>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
            <div id="page2" hidden>
                <table class="table">
                    <tr>
                        <td>Email<br>
                            <span id="email-text" class="red-text"></span></td>
                        <td>{{userform.username|attr:"onkeyup=this.value=this.value.toUpperCase()"}}</td>
                    </tr>
                    <tr>
                        <td>
                            <button type="button" id="otpGen" onclick="otpGenerator()">Generate Otp</button>
                            <input type="text" id="otp" hidden placeholder="Otp" style="width:130px;">
                        </td>
                        <td>
                            <button type="button" id="valid-btn" onclick="otpValidator()" hidden>Validate</button>
                            <button type="button" id="resend-btn" onclick="otpGenerator()" hidden>Resend Otp</button>
                            <span id="resend-text"> </span>
                        </td>
                    </tr>
                    <tr>
                        <td>Password</td>
                        <td>{{ userform.password|attr:"type=password" }}</td>
                    </tr>
                    <tr>
                        <td>Confirm Password</td>
                        <td><input type="password" id="confirm_pass" oninput="matchingOfPassword()"><br>
                            <span id="password_text" class="red-text"></span></td>
                    </tr>
                    <tr>
                        <td>
                            <font size="12">
                                <a class="material-tooltip-main" data-toggle="tooltip"
                                   title="Next" onclick="previousPage()">&#9664;
                                </a>
                            </font>
                        </td>
                        <td>
                            {{userform.is_warden_owner|attr:"hidden"|attr:"checked"}}
                            <button class="btn blue-gradient" type="button" onclick="submitForm()">Submit</button>
                        </td>
                    </tr>
                </table>
            </div>
        </form>
    </div>
</div>
{%endblock%}

hostelapp/templates/hostler.html
{% extends 'extends/hostler_extends.html' %}
{% block content%}
<div class="container w-50" align="center">
    <div class="row mt-5 z-depth-3 w-75" style="background:#5CF7E7;">
        <div class="col-6 my-5 " >
            <a class="nav-link  li-margin" href="/hostler/complain/">COMPLAIN</a>
        </div>
    </div>
    <div class="row mt-5 my-5 z-depth-3 w-75" style="background:#5CF7E7;">
        <div class="col-6 my-5" >
            <a class="nav-link  li-margin" href="/hostler/complain_status/">COMPLAIN&nbsp;STATUS</a>
        </div>
    </div>
    <div class="row mt-5 z-depth-3 w-75" style="background:#5CF7E7;">
        <div class="col-6 my-5" >
            <a class="nav-link  li-margin" href="/hostler/receipt/">RECEIPT</a>
        </div>
    </div>
</div>
{% endblock %}

hostelapp/templates/hostler_complain.html
{% extends 'extends/hostler_extends.html' %}
{% block content%}
<div class="container my-5 w-50">
    <div class="my-5">
        <form action="/hostler/complain/" method="post">{% csrf_token %}
            <div class="md-form ">
                <i class="fas fa-user prefix"></i>
                <input type="text" name="subject" id="subject" class="form-control" style="height:70px;" required>
                <label for="subject">Subject</label>
            </div>
            <div class="md-form mt-3">
                <i class="fas fa-user prefix"></i>
                <textarea name="message" id="message" class="form-control md-textarea" style="height:200px;" required></textarea>
                <label for="message">Message</label>
            </div>
            <div align="center" class="my-5">
            <input type="submit" value="Register Complain" class="btn btn-info">
            </div>
        </form>
    </div>
</div>
{% endblock%}

hostelapp/templates/hostler_complain_status.html
{% extends 'extends/hostler_extends.html' %}
{% block content %}
<div class="container mt-5 w-50">
    <div class="mt-5" align="center"><h2>Complain Status</h2></div>
    <table class="w-100" border="1">
        <tr>
            <td>Date</td>
            <td>Subject</td>
            <td>Message</td>
            <td>Status</td>
        </tr>
        {% for i in data %}
        <tr>
            <td>{{i.date}}</td>
            <td>{{i.subject}}</td>
            <td>{{i.message}}</td>
            <td>{{i.complain_status}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

hostelapp/templates/loginpage.html
{% extends 'extends/basic.html' %}
{% load static %}
{% load widget_tweaks%}
{% block style %}
<style>
body,html{
    height:100%;}
    .vertical-center {
      margin: 0;
      position: absolute;
      top: 50%;
      -ms-transform: translateY(-50%);
      transform: translateY(-50%);
    }


</style>
{% endblock %}
{% block body %}
<div style="background-image:url({% static 'images/hostel2.jpg' %}); height:100%;background-position: center;background-size: cover;">
    <div style="background-color:rgba(0,0,0,0.5);height:100%;">
        <div class="white-text" align="center" style="font-size:40px;background-color:rgba(0,0,0,0.8);">
            <b>ONLINE HOSTEL MANAGEMENT</b>
        </div>
        <div style="height:30%;"></div>
        <div class="row mx-5">
            <div class="container col-md-3 " align="center"
                 style="background-color:rgba(0,0,0,0.5);padding-top:20px;padding-bottom:50px;">
                <div class="white-text my-2" style="font-size:25px;">
                    <b>SIGN IN</b></div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    {% if message.tags %}
                    <li class="red-text">{{ message }}</li>
                    {% endif %}
                    {% endfor %}
                </ul>
                {% endif %}
                <form method="post" action="/login_details/" autocomplete="off">{% csrf_token %}
                    <div class="md-form ">
                        <i class="fas fa-user prefix"></i>
                        {{form.username|add_class:"form-control"|attr:"onkeyup=this.value=this.value.toUpperCase()"}}
                        <label for="id_username" class="white-text">E-mail address</label>
                    </div>
                    <div class="md-form">
                        <i class="fas fa-user prefix"></i>
                        {{form.password|add_class:"form-control"}}
                        <label for="id_password" class="white-text">Password</label>
                    </div>
                    <div class="white-text"><a href="" data-toggle="modal" data-target="#forgot_password">Forgot Password</a></div>
                    <input type="submit" class="btn btn-light" value="log-in">
                </form>
            </div>
            <div class="col-md-5">
                <div style="width:70%;background-color:rgba(0,0,0,0.5);height:100%;">
                    <a href="/hostel_register/" class="vertical-center white-text"
                       style="font-size:25px;margin-left:60px;">
                        REGISTER YOUR HOSTEL
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

hostelapp/templates/logout.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Sorry, you are logged out</title>
</head>
<body>
<h1>You are logged out</h1>
<center>
    <div style="width:60%;border:1px solid;font-size:25px;">
        <p style="margin-top:50px;margin-bottom:50px;">
            you pressed the logout button <br>
            go to the<a href="/"> home page</a><br>
        </p>
    </div>
</center>
</body>
</html>

hostelapp/templates/payment.html
{% extends 'extends/hostel_admin_extends.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="container mt-3 w-50">
    <div align="right"><a href="/hostel_admin/payment_list/">All Payment</a></div>
    <div align="center"><h2>Payment</h2></div>
    <form action="/hostel_admin/payment/" method="post" autocomplete="off">{% csrf_token %}
        <table cellpadding="5" align="center" class="table w-100">
            <tr>
                <td>Receipt no.</td>
                <td><input type="number" value="{{slip_number}}" name="slip_no"></td>
                <td>Date :</td>
                <td><input type="date" name="date"></td>
            </tr>
            <tr>
                <td>Name</td>
                <td>
                    <select style="width:100%;" name="name">
                        <option value="">Name</option>
                        {% for n in names %}
                        <option value="{{n}}">{{n|title}}</option>
                        {% endfor %}
                    </select></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>Amount</td>
                <td><input type="number" name="amount"></td>
                <td>Month and year</td>
                <td><input type="month" name="month_year"></td>
            </tr>
            <tr>
                <td>Remark</td>
                <td colspan="3"><textarea name="remark" style="width:400px;"></textarea></td>
            </tr>
        </table>
        <div align="center" class="mt-5">
            <input type="submit" value="Save" class="btn morpheus-den-gradient white-text">
        </div>
    </form>
</div>
{% endblock %}